In [2]:
import pandas as pd

# 读取数据 usecols -> 指定读取的列
df = pd.read_csv('data/sales.csv', usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'])

# 计算销售额
df['销售额'] = df['销售数量'] * df['单价']

# 写出csv数据 index=False -> 不写索引列
df.to_csv('data/sales_output.csv', index=False)

In [12]:
# 数据查看 --> head , tail , describe , info , shape , columns
df1 = pd.read_csv('data/sales.csv', usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'])

df1.head(10)  # 查看前10行
df1.tail(10)  # 查看最后10行
df1.describe()  # 查看数据统计信息
df1.info()  # 查看数据信息(列名,非空计数,类型)
df1.shape  # 查看数据行数和列数
df1.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     1000 non-null   int64
 1   产品类别    1000 non-null   object
 2   产品名称    1000 non-null   object
 3   销售数量    1000 non-null   int64
 4   单价      1000 non-null   int64
dtypes: int64(3), object(2)
memory usage: 39.2+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价'], dtype='object')

In [3]:
# 数据选择
df2 = pd.read_csv('data/sales.csv', usecols=['订单号', '产品类别', '产品名称', '销售数量', '单价'], index_col='订单号')

# 1.选择列
df2['产品名称']
df2[['产品名称', '单价']]

# 2.选择行
# iloc:基于 行号 选择行,不包含结束行
df2.iloc[0:5:1]
# loc:基于 索引 选择行,包含结束行
df2.loc[6805677496:5897064217]

            产品类别  产品名称  销售数量   单价
订单号
6805677496  家居用品    枕头    10  199
5857234132    食品    海苔     5   29
5888085059  电子产品  智能音箱     5  399
6823473137    食品    面包     3   29
6801664364    食品    薯片     2   19
5897064217    图书    字帖     4   29

In [9]:
df3 = pd.read_csv('data/sales.csv')

# 数据过滤 ---> df[filter]
# 1. 获取 销售数量 >= 10 的订单数据
df3[df3['销售数量'] >= 10]

# 2. 获取产品类别为 食品 或 图书 的订单数据
df3[df3['产品类别'].isin(['食品', '图书'])]

# 3. 获取 单价在100-200之间 的订单数据 ---> 范围: between ---> 默认包含边界
df3[df3['单价'].between(100, 200, inclusive='both')]

# 4. 获取 销售数量 >= 8 , 并且 单价 >= 100 的订单数据 ----> 多条件(并且: & , 或者: |)
df3[(df3['销售数量'] >= 8) & (df3['单价'] >= 100)]

# 5. 获取 产品类别为 服装/食品 ， 支付方式为 支付宝/微信支付 的订单数据
df3[(df3['产品类别'].isin(['服装', '食品'])) & (df3['支付方式'].isin(['支付宝', '微信支付']))]

            订单号 产品类别 产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
4    6801664364   食品   薯片     2   19    NaN  微信支付  2025-06-02
10   5808071569   食品  矿泉水     9   29     重庆   支付宝  2025-06-04
16   5812573980   食品   坚果     2   79     南京  微信支付  2025-06-05
23   6867258691   服装   围巾     8  129     青岛  微信支付  2025-06-07
25   6837065480   服装   毛衣     3  399     深圳  微信支付  2025-06-07
..          ...  ...  ...   ...  ...    ...   ...         ...
993  6870828210   服装   内衣     8   89     广州  微信支付  2026-03-20
994  5860722276   服装   外套     6  599     广州  微信支付  2026-03-20
996  5808511756   食品   坚果     2   79     成都   支付宝  2026-03-20
997  5811169466   服装   围巾     4  129     南京   支付宝  2026-03-20
998  6876456690   食品   果汁     7   39     广州   支付宝  2026-03-20

[297 rows x 8 columns]